# Generated by Django 2.2.7 on 2019-11-21 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191121_1415'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='list',
            new_name='infinido',
        ),
    ]
