# Generated by Django 2.2.7 on 2019-11-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191121_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infinido',
            name='parent',
            field=models.CharField(default=-1, max_length=100),
        ),
    ]
