# Generated by Django 2.2.7 on 2019-11-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191121_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infinido',
            name='parent',
            field=models.IntegerField(default=-1),
        ),
    ]
